#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Load settings"

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE MYSQL DATABASE
#=================================================
ynh_print_info "Remove the mysql database"

# Remove a database if it exists, along with the associated user
ynh_mysql_remove_db $db_name $db_name

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_print_info "Remove app main directory"

# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_print_info "Remove nginx configuration"

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_print_info "Remove php-fpm configuration"

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE GPG KEY
#=================================================

gpg --batch --delete-key --yes Rainloop

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_print_info "Remove the dedicated user"

# Delete a system user
ynh_system_user_delete $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Deletion completed"
